import streamlit as st
import pickle 
import string 
import nltk 
from nltk.corpus import stopwords 
from nltk.stem.porter import PorterStemmer 

# Download stop words just in case
nltk.download("stopwords", quiet=True)
stemmer = PorterStemmer()
stopwords_set = set(stopwords.words("english"))

# Load the saved pickle files from your folder
model_file = open("pickel_files/model.pkl", "rb")
clf = pickle.load(model_file)

vectorizer_file = open("pickel_files/vectorizer.pkl", "rb")
vectorizer = pickle.load(vectorizer_file)

# Basic Front end part
st.title("BOT-OR-NOT Detector")
st.write("Paste an Instagram bio, comment, or email below to see if it was written by a bot or an actual person")
user_input = st.text_area("Enter Text Here!")

# When user clicks
if st.button("Analyze Text"):
    if user_input:
        text = user_input.lower()
        text = text.translate(str.maketrans("","",string.punctuation)).split()

        
        text = [stemmer.stem(word) for word in text if word not in stopwords_set]
        cleaned_input = " ".join(text)

       
        vectorized_input = vectorizer.transform([cleaned_input]).toarray()


        prediction = clf.predict(vectorized_input)[0]

        if prediction == 1:
            st.error("Alert: This text was likely generated by a BOT or it is likely a SPAM.")
        else:
            st.success("SAFE: This text looks like it was written by a HUMAN and likely is not SPAM")
    else:
        st.warning("You need to paste some text first!")