import streamlit as st
import pickle 
import string 
import nltk 
from nltk.corpus import stopwords 
from nltk.stem.porter import PorterStemmer 

# Download stop words just in case
nltk.download("stopwords", quiet=True)
stemmer = PorterStemmer()
stopwords_set = set(stopwords.words("english"))

# Load the saved pickle files from your folder
model_file = open("pickel_files/model.pkl", "rb")
clf = pickle.load(model_file)
 
vectorizer_file = open("pickel_files/vectorizer.pkl", "rb")
vectorizer = pickle.load(vectorizer_file)

# Basic Front end part
st.title("BOT-OR-NOT Detector")
st.info("**Model Details:** This AI is specifically trained to detect malicious social media bots, phishing attempts, and traditional spam. **Note:** It is NOT currently trained to detect modern Large Language Models (like ChatGPT) writing normal essays.")
st.write("Paste an Instagram bio, comment, or email below to see if it was written for scamming you or its normal and not a spam")

# Fixed indentation and removed the backslash here
sample_choice = st.selectbox(
    "Try a sample or write your own:",
    ["Write my own....(Please keep it a bit long)", "Human Sample", "Spam Bot Sample"]
)

default_text = ""
if sample_choice == "Human Sample":
    default_text = "Hey man, are we still on for the meeting tomorrow at 3 PM? Let me know."
elif sample_choice == "Spam Bot Sample":
    default_text = "CONGRATULATIONS! You won a FREE $1000 gift card! Click here to claim your prize now!!!"

user_input = st.text_area("Enter Text Here!", value=default_text)

# When user clicks then lets make it analyze the text
if st.button("Analyze Text"):
    if user_input:
        text = user_input.lower()
        text = text.translate(str.maketrans("","",string.punctuation)).split()
        
        text = [stemmer.stem(word) for word in text if word not in stopwords_set]
        cleaned_input = " ".join(text)
    
        vectorized_input = vectorizer.transform([cleaned_input]).toarray()
        prediction = clf.predict(vectorized_input)[0]

        # Added the missing confidence math here
        probabilities = clf.predict_proba(vectorized_input)[0]
        confidence = probabilities[prediction] * 100

        # Added the f-strings to display the confidence
        if prediction == 1:
            st.error("Alert: This text was likely generated by a BOT or it is likely a SPAM.")
            st.write(f"**AI Confidence:** {confidence:.2f}%")
        else:
            st.success("SAFE: This text looks like it was written by a HUMAN and likely is not SPAM")
            st.write(f"**AI Confidence:** {confidence:.2f}%")
    else:
        st.warning("You need to paste some text first!") 